# Generated by Django 3.0.8 on 2020-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
